default:
  aws_access_key_id: 'AKIAJETETNUJ3524FKVA'       # required
  aws_secret_access_key: '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'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'
