default:
  aws_access_key_id: 'AKIAJWNKSGKPZF6REPDA'    # required
  aws_secret_access_key: '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'  # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'
